# Phase 1

I have collected the below data from two places and club those together in one file 

1. https://www.kaggle.com/datasets/gokulrajkmv/indian-statewise-data-from-rbi
2. https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
    
these are two sites from where I gatheres data

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv('C://Users//ASHTABHUJA//Downloads//cluster.csv')
data

,States_Union Territories,2000-01-INC,2011-12-INC,2001 - LIT,2011- LIT,2001 - POP,2011- POP,2001 -SEX_Ratio,2011 -SEX_Ratio,2001 -UNEMP,2011 -UNEMP,2001 -Poverty,2011 -Poverty,State /,Area (km2)
0,Andaman and Nicobar Islands,25047.0,89642.0,81.30,86.63,356.0,381.0,846.0,876.0,34.0,54.0,20.99,1.00,Union Territory,NaN
1,Andhra Pradesh,17195.0,64773.0,60.47,67.02,76210.0,84581.0,978.0,993.0,8.0,12.0,15.77,9.20,Rajasthan,"3,42,239"
2,Arunachal Pradesh,15260.0,71366.0,54.34,65.39,1098.0,1384.0,893.0,938.0,5.0,17.0,33.47,34.67,Madhya Pradesh,"3,08,252"
3,Assam,12803.0,36320.0,63.25,72.19,26656.0,31206.0,935.0,958.0,39.0,45.0,36.09,31.98,Maharashtra,"3,07,713"
4,Bihar,6415.0,22582.0,47.00,61.80,82999.0,104099.0,919.0,918.0,18.0,32.0,42.60,33.74,Uttar Pradesh,"2,40,928"
5,Chandigarh,49771.0,136883.0,81.94,86.05,901.0,1055.0,777.0,818.0,7.0,24.0,5.75,21.81,Gujarat,"1,96,024"
6,Chhattisgarh,10744.0,48366.0,64.66,70.28,20834.0,25545.0,989.0,991.0,16.0,8.0,30.00,39.93,Karnataka,"1,91,791"
7,Delhi,40678.0,161446.0,57.63,76.24,13851.0,16788.0,821.0,868.0,47.0,78.0,8.23,9.91,Andhra Pradesh,"1,62,975"
8,Goa,43735.0,211570.0,78.18,87.10,1348.0,1459.0,961.0,973.0,93.0,51.0,4.40,5.09,Odisha,"1,55,707"
9,Gujarat,18392.0,85979.0,81.67,86.21,50671.0,60440.0,920.0,919.0,4.0,3.0,14.07,16.63,Chhattisgarh,"1,35,192"
10,Haryana,25583.0,106320.0,82.01,88.70,21145.0,25351.0,861.0,879.0,8.0,24.0,8.74,11.16,Tamil Nadu,"1,30,058"
11,Himachal Pradesh,22795.0,75185.0,69.14,78.03,6078.0,6865.0,968.0,972.0,12.0,10.0,7.63,8.06,Telangana,"1,12,077"
12,Jammu and Kashmir,14268.0,46734.0,67.91,75.55,10144.0,12541.0,892.0,889.0,11.0,25.0,3.48,10.35,Bihar,"94,163"
13,Jharkhand,10345.0,36554.0,76.48,82.80,26946.0,32988.0,941.0,948.0,20.0,21.0,32.00,36.96,West Bengal,"88,752"
14,Karnataka,18344.0,68053.0,55.52,67.16,52851.0,61095.0,965.0,973.0,7.0,9.0,20.04,20.91,Arunachal Pradesh,"83,743"
15,Kerala,20094.0,82753.0,53.56,66.41,31841.0,33406.0,1058.0,1084.0,82.0,68.0,12.72,7.05,Jharkhand,"79,716"
16,Madhya Pradesh,11862.0,37180.0,66.60,75.37,60348.0,72627.0,919.0,931.0,5.0,4.0,37.43,31.65,Assam,"78,438"
17,Maharashtra,22777.0,93282.0,90.86,94.00,96879.0,112374.0,922.0,929.0,14.0,7.0,25.02,17.35,Ladakh,"59,146"
18,Manipur,12369.0,33695.0,86.66,91.85,2294.0,2856.0,978.0,992.0,19.0,26.0,28.54,36.89,NaN,"-1,66,698"
19,Meghalaya,15657.0,50316.0,63.74,69.32,2319.0,2967.0,972.0,989.0,4.0,4.0,33.87,11.87,Himachal Pradesh,"55,673"
20,Mizoram,17826.0,53624.0,76.88,82.34,889.0,1097.0,935.0,976.0,9.0,18.0,19.47,20.40,Uttarakhand,"53,483"
21,Nagaland,16253.0,63781.0,70.50,76.90,1990.0,1979.0,900.0,931.0,24.0,151.0,32.67,18.88,Punjab,"50,362"
22,Odisha,10453.0,43463.0,62.56,74.43,36805.0,41974.0,972.0,979.0,19.0,22.0,47.15,32.59,Haryana,"44,212"
23,Puducherry,35994.0,103149.0,88.80,91.33,974.0,1248.0,1001.0,1037.0,40.0,8.0,21.67,9.69,Jammu and Kashmir,"42,241"
24,Punjab,27881.0,76895.0,66.59,79.60,24359.0,27743.0,876.0,895.0,18.0,19.0,6.16,8.26,NaN,"-55,538"
25,Rajasthan,13020.0,54637.0,63.08,72.89,56507.0,68548.0,921.0,928.0,4.0,7.0,15.28,14.71,Kerala,"38,863"
26,Sikkim,16077.0,130127.0,81.24,85.85,541.0,611.0,875.0,890.0,28.0,10.0,36.55,8.19,Meghalaya,"22,429"
27,Tamil Nadu,20972.0,89050.0,69.65,75.84,62406.0,72147.0,987.0,996.0,20.0,20.0,21.12,11.28,Manipur,"22,327"
28,Tripura,15983.0,50859.0,68.81,81.42,3199.0,3674.0,948.0,960.0,12.0,105.0,34.44,14.05,Mizoram,"21,081"
29,Uttar Pradesh,9828.0,30021.0,73.45,80.09,166198.0,199812.0,898.0,912.0,8.0,9.0,31.15,29.43,Nagaland,"16,579"
30,Uttarakhand,15285.0,85372.0,73.19,87.22,8489.0,10086.0,962.0,963.0,22.0,25.0,10.56,11.26,Tripura,"10,491"
31,West Bengal,16583.0,53383.0,56.27,67.68,80176.0,91276.0,934.0,950.0,28.0,27.0,27.02,19.98,Andaman and Nicobar Islands,"8,249"
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sikkim,"7,096"
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Goa,"3,702"
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delhi,"1,484"
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dadra and Nagar Haveli and Daman and Diu,603
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Puducherry,479
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chandigarh,114
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lakshadweep,32

1. The population of each state.

In [5]:
data['2001 - POP']

0        356.0
1      76210.0
2       1098.0
3      26656.0
4      82999.0
5        901.0
6      20834.0
7      13851.0
8       1348.0
9      50671.0
10     21145.0
11      6078.0
12     10144.0
13     26946.0
14     52851.0
15     31841.0
16     60348.0
17     96879.0
18      2294.0
19      2319.0
20       889.0
21      1990.0
22     36805.0
23       974.0
24     24359.0
25     56507.0
26       541.0
27     62406.0
28      3199.0
29    166198.0
30      8489.0
31     80176.0
32         NaN
33         NaN
34         NaN
35         NaN
36         NaN
37         NaN
38         NaN
Name: 2001 - POP, dtype: float64

2. Literacy Rate in each state

In [6]:
data['2001 - LIT']

0     81.30
1     60.47
2     54.34
3     63.25
4     47.00
5     81.94
6     64.66
7     57.63
8     78.18
9     81.67
10    82.01
11    69.14
12    67.91
13    76.48
14    55.52
15    53.56
16    66.60
17    90.86
18    86.66
19    63.74
20    76.88
21    70.50
22    62.56
23    88.80
24    66.59
25    63.08
26    81.24
27    69.65
28    68.81
29    73.45
30    73.19
31    56.27
32      NaN
33      NaN
34      NaN
35      NaN
36      NaN
37      NaN
38      NaN
Name: 2001 - LIT, dtype: float64

3. Area of each state

In [7]:
data['Area (km2)']

0           NaN
1      3,42,239
2      3,08,252
3      3,07,713
4      2,40,928
5      1,96,024
6      1,91,791
7      1,62,975
8      1,55,707
9      1,35,192
10     1,30,058
11     1,12,077
12       94,163
13       88,752
14       83,743
15       79,716
16       78,438
17       59,146
18    -1,66,698
19       55,673
20       53,483
21       50,362
22       44,212
23       42,241
24      -55,538
25       38,863
26       22,429
27       22,327
28       21,081
29       16,579
30       10,491
31        8,249
32        7,096
33        3,702
34        1,484
35          603
36          479
37          114
38           32
Name: Area (km2), dtype: object